/* ERT */

INSERT INTO races (id, parent_race, name, attributes_physical, attributes_mental, attributes_spiritual, balance_law, balance_magic, balance_chaos, life_multiplier) VALUES ( 1, 'Melion',  'Alsano',    11, 10, 11, 1, 2, 1,  8);
INSERT INTO races (id, parent_race, name, attributes_physical, attributes_mental, attributes_spiritual, balance_law, balance_magic, balance_chaos, life_multiplier) VALUES ( 2, 'Melion',  'Kenion',    11, 11, 11, 1, 3, 1,  8);
INSERT INTO races (id, parent_race, name, attributes_physical, attributes_mental, attributes_spiritual, balance_law, balance_magic, balance_chaos, life_multiplier) VALUES ( 3, 'Melion',  'Mirr',      12,  9,  9, 1, 2, 1, 10);
INSERT INTO races (id, parent_race, name, attributes_physical, attributes_mental, attributes_spiritual, balance_law, balance_magic, balance_chaos, life_multiplier) VALUES ( 4, 'Melion',  'Taerita',   11,  8, 11, 1, 2, 1,  8);
INSERT INTO races (id, parent_race, name, attributes_physical, attributes_mental, attributes_spiritual, balance_law, balance_magic, balance_chaos, life_multiplier) VALUES ( 5, 'Melion',  'Moellan',   11,  9, 10, 1, 2, 1,  8);
INSERT INTO races (id, parent_race, name, attributes_physical, attributes_mental, attributes_spiritual, balance_law, balance_magic, balance_chaos, life_multiplier) VALUES ( 6, 'Melion',  'Samnio',     8,  9, 12, 1, 3, 1,  8);
INSERT INTO races (id, parent_race, name, attributes_physical, attributes_mental, attributes_spiritual, balance_law, balance_magic, balance_chaos, life_multiplier) VALUES ( 7, 'Dweloin', 'Pearoin',   14, 10,  8, 1, 1, 2, 10);
INSERT INTO races (id, parent_race, name, attributes_physical, attributes_mental, attributes_spiritual, balance_law, balance_magic, balance_chaos, life_multiplier) VALUES ( 8, 'Selion',  'Nethan',    13,  8, 10, 1, 2, 1,  9);
INSERT INTO races (id, parent_race, name, attributes_physical, attributes_mental, attributes_spiritual, balance_law, balance_magic, balance_chaos, life_multiplier) VALUES ( 9, 'Ywen',    'Celestial',  9, 12, 10, 2, 2, 1,  8);
INSERT INTO races (id, parent_race, name, attributes_physical, attributes_mental, attributes_spiritual, balance_law, balance_magic, balance_chaos, life_multiplier) VALUES (10, 'Ywen',    'Amanecer',  12, 11,  8, 2, 2, 1,  7);

INSERT INTO racial_gifts (id, race_id, name) VALUES ( 1,  1, 'Bueno para Todo');
INSERT INTO racial_gifts (id, race_id, name) VALUES ( 2,  1, 'Experto Artesano');
INSERT INTO racial_gifts (id, race_id, name) VALUES ( 3,  2, 'Preparación Militar');
INSERT INTO racial_gifts (id, race_id, name) VALUES ( 4,  2, 'Conocimientos en Historia Antigua');
INSERT INTO racial_gifts (id, race_id, name) VALUES ( 5,  2, 'Magia Global');
INSERT INTO racial_gifts (id, race_id, name) VALUES ( 6,  3, 'Resistencia a las Enfermedades');
INSERT INTO racial_gifts (id, race_id, name) VALUES ( 7,  3, 'Comprensión de la Naturaleza');
INSERT INTO racial_gifts (id, race_id, name) VALUES ( 8,  3, 'Empatía Animal');
INSERT INTO racial_gifts (id, race_id, name) VALUES ( 9,  4, 'Manto de Sombras');
INSERT INTO racial_gifts (id, race_id, name) VALUES (10,  4, 'Dotado para los Dones del Caos');
INSERT INTO racial_gifts (id, race_id, name) VALUES (11,  4, 'Inmune a los Venenos Naturales');
INSERT INTO racial_gifts (id, race_id, name) VALUES (12,  4, 'Conocimiento en Venenos');
INSERT INTO racial_gifts (id, race_id, name) VALUES (13,  4, 'Equipo Inicial: Daga Kr');
INSERT INTO racial_gifts (id, race_id, name) VALUES (14,  4, 'Equipo Inicial: Dos Venenos a elegir');
INSERT INTO racial_gifts (id, race_id, name) VALUES (15,  5, 'Equipo Inicial: Caballo Moellan');
INSERT INTO racial_gifts (id, race_id, name) VALUES (16,  5, 'Empatía con los Caballos');
INSERT INTO racial_gifts (id, race_id, name) VALUES (17,  5, 'Vista Aguda');
INSERT INTO racial_gifts (id, race_id, name) VALUES (18,  5, 'Experto Rastreador');
INSERT INTO racial_gifts (id, race_id, name) VALUES (19,  6, 'Ojos de Estrellas');
INSERT INTO racial_gifts (id, race_id, name) VALUES (20,  6, 'Aptitud Natural para la Magia');
INSERT INTO racial_gifts (id, race_id, name) VALUES (21,  7, 'Piel Resistente');
INSERT INTO racial_gifts (id, race_id, name) VALUES (22,  7, 'Doble Corazón');
INSERT INTO racial_gifts (id, race_id, name) VALUES (23,  7, 'Sangre de Metal');
INSERT INTO racial_gifts (id, race_id, name) VALUES (24,  8, 'Ojos de Gato');
INSERT INTO racial_gifts (id, race_id, name) VALUES (25,  8, 'Sentidos Agudizados');
INSERT INTO racial_gifts (id, race_id, name) VALUES (26,  8, 'Afinidad con los Felinos');
INSERT INTO racial_gifts (id, race_id, name) VALUES (27,  8, 'Garras');
INSERT INTO racial_gifts (id, race_id, name) VALUES (28,  9, 'Acostumbrado a las Alturas');
INSERT INTO racial_gifts (id, race_id, name) VALUES (29,  9, 'Levitación');
INSERT INTO racial_gifts (id, race_id, name) VALUES (30,  9, 'Dones del Viento');
INSERT INTO racial_gifts (id, race_id, name) VALUES (31, 10, 'Fuerza del Amanecer');
INSERT INTO racial_gifts (id, race_id, name) VALUES (32, 10, 'Maestría en Trato con Otras Razas');
